// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABOz_Mv7i-sxuFQStpLLnV-WA3Sd5oavY',
    appId: '1:846190937468:web:bc8f1becd60575d5dad0f9',
    messagingSenderId: '846190937468',
    projectId: 'food-fus',
    authDomain: 'food-fus.firebaseapp.com',
    storageBucket: 'food-fus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNqDXqj5finhPSLre4hUwQDb1gaykBOPE',
    appId: '1:846190937468:android:12edc585993dc415dad0f9',
    messagingSenderId: '846190937468',
    projectId: 'food-fus',
    storageBucket: 'food-fus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAF9vwcsv6wNcpO9EC3Ntztzx2pRnELJ0',
    appId: '1:846190937468:ios:6d436277d1a75a1fdad0f9',
    messagingSenderId: '846190937468',
    projectId: 'food-fus',
    storageBucket: 'food-fus.appspot.com',
    iosBundleId: 'com.csv.json.app',
  );
}
